import type { BankLevel, Exercise } from '../../exercises/types';
import { buildLevel, type LevelBankSource } from './builders';

/**
 * English exercise bank, A1 → C1. Meanings are simple English definitions
 * (monolingual), so translations are left empty.
 */
const EN: Record<BankLevel, LevelBankSource> = {
  A1: {
    vocab: [
      ['brother', 'a boy or man with the same parents as you', 'My brother is twelve.'],
      ['breakfast', 'the first meal of the day', 'I have breakfast at seven.'],
      ['cheap', 'not expensive', 'This shirt is very cheap.'],
      ['expensive', 'costs a lot of money', 'The hotel is expensive.'],
      ['street', 'a road in a town', 'I live on Green Street.'],
      ['tired', 'needing to rest or sleep', 'I’m tired after work.'],
      ['hungry', 'wanting to eat', 'Are you hungry?'],
      ['always', 'every time', 'She always drinks tea.'],
      ['never', 'not at any time', 'I never eat meat.'],
      ['buy', 'to get something by paying money', 'I buy bread every day.'],
      ['open', 'not closed', 'The shop is open until six.'],
      ['near', 'not far', 'The bank is near the station.'],
      ['weekend', 'Saturday and Sunday', 'What do you do at the weekend?'],
      ['job', 'the work you do for money', 'I like my job.'],
      ['ticket', 'a paper that lets you travel or enter', 'One ticket to London, please.'],
      ['how much', 'used to ask the price', 'How much is this?'],
    ],
    grammar: [
      { c: 'She ___ from Brazil.', a: 'is', why: 'To be: I am, you are, he/she/it is.' },
      { c: 'They ___ in a small flat.', a: 'live', why: 'Present simple: no -s with they.' },
      { c: 'He ___ coffee every morning.', a: 'drinks', hint: 'drink', why: 'Add -s with he/she/it.' },
      { c: '___ you like pizza?', a: 'Do', why: 'Questions in present simple: Do + subject + verb.' },
      { c: 'She ___ like cold weather.', a: ["doesn't", 'does not'], why: 'Negative with he/she/it: doesn’t + verb.' },
      { c: 'There ___ two chairs in the room.', a: 'are', why: 'There are + plural.' },
      { m: 'I have ___ apple.', o: ['a', 'an', 'the', '—'], a: 1, why: 'An before a vowel sound.' },
      { m: 'This is ___ book. (it belongs to me)', o: ['me', 'my', 'mine', 'I'], a: 1 },
      { m: 'The keys are ___ the table.', o: ['in', 'on', 'at', 'to'], a: 1 },
      { order: 'What time do you get up', tr: '' },
      { order: 'My sister is a nurse in London', tr: '' },
    ],
    dictation: [
      ['My name is Anna and I am a student.', ''],
      ['The shop opens at nine o’clock.', ''],
      ['I have two brothers and one sister.', ''],
      ['Can I have a glass of water, please?', ''],
      ['We live near the station.', ''],
    ],
    dialogues: [
      {
        title: 'At the café',
        lines: ['Hi! What can I get you?', 'A cappuccino and a muffin, please.', 'Eat in or take away?', 'Take away, please. How much is that?', 'That’s four pounds twenty.'],
        questions: [
          ['What does the customer order?', ['Tea and a cake', 'A cappuccino and a muffin', 'Two coffees', 'A sandwich'], 1],
          ['Where will the customer eat?', ['In the café', 'Take away', 'At work', 'We don’t know'], 1],
          ['How much does it cost?', ['£2.40', '£4.20', '£4.02', '£14.20'], 1],
        ],
      },
      {
        title: 'Meeting a neighbour',
        lines: ['Hello, I’m Kate. I live at number six.', 'Hi Kate, I’m Omar. I’m new here.', 'Welcome! Where are you from?', 'I’m from Egypt. I work at the hospital.'],
        questions: [
          ['Where does Kate live?', ['At number two', 'At number six', 'At the hospital', 'In Egypt'], 1],
          ['Where is Omar from?', ['England', 'Egypt', 'Morocco', 'Spain'], 1],
          ['Where does Omar work?', ['At a school', 'At a bank', 'At the hospital', 'At a café'], 2],
        ],
      },
    ],
    repeat: [
      ['Nice to meet you.', ''],
      ['Excuse me, where is the station?', ''],
      ['Sorry, I don’t understand. Can you repeat that?', ''],
      ['I’d like a coffee, please.', ''],
      ['What do you do at the weekend?', ''],
    ],
    speak: [
      { prompt: 'Introduce yourself: your name, where you are from and where you live.', targets: ['my name is', "i'm from", 'i live in'], seconds: 45, model: 'Hi, my name is Léa. I’m from France and I live in Lyon.' },
      { prompt: 'Describe your family.', targets: ['i have', 'his name is', 'her name is', 'years old'], seconds: 60 },
      { prompt: 'What do you like and not like eating?', targets: ['i like', "i don't like", 'my favourite'], seconds: 45 },
      { prompt: 'Order food and a drink in a café.', targets: ["i'd like", 'please', 'how much'], seconds: 30 },
    ],
  },
  A2: {
    vocab: [
      ['journey', 'a trip from one place to another', 'The journey took three hours.'],
      ['book (verb)', 'to reserve in advance', 'I booked a table for two.'],
      ['luggage', 'the bags you take when you travel', 'My luggage is too heavy.'],
      ['headache', 'a pain in your head', 'I’ve got a terrible headache.'],
      ['last week', 'the week before this one', 'I was in Paris last week.'],
      ['ago', 'before now', 'I moved here two years ago.'],
      ['borrow', 'to take something and give it back later', 'Can I borrow your pen?'],
      ['lend', 'to give something for a short time', 'I’ll lend you my car.'],
      ['turn left', 'go to the left', 'Turn left at the bank.'],
      ['go straight on', 'continue in the same direction', 'Go straight on for 200 metres.'],
      ['try on', 'to put on clothes to see if they fit', 'Can I try on these jeans?'],
      ['usually', 'most of the time', 'I usually walk to work.'],
      ['bored', 'not interested; with nothing to do', 'I was bored at the party.'],
      ['boring', 'not interesting', 'The film was boring.'],
      ['arrive', 'to reach a place', 'We arrived late.'],
      ['miss (a train)', 'to be too late for', 'I missed the last bus.'],
    ],
    grammar: [
      { c: 'Yesterday I ___ to the cinema.', a: 'went', hint: 'go', why: 'Past simple of go: went.' },
      { c: 'We ___ a great film last night.', a: 'saw', hint: 'see' },
      { c: '___ you enjoy the party?', a: 'Did', why: 'Past questions: Did + subject + base verb.' },
      { c: 'I ___ dinner when you called.', a: 'was having', hint: 'have', why: 'Past continuous for an action in progress.' },
      { c: 'I’m ___ to visit my grandparents tomorrow.', a: 'going', why: 'Be going to for plans.' },
      { c: 'This film is ___ than the book.', a: 'better', why: 'Irregular comparative: good → better.' },
      { c: 'It’s the ___ restaurant in town.', a: ['best'], hint: 'good', why: 'Superlative: the best.' },
      { m: 'I’ve lived here ___ 2019.', o: ['for', 'since', 'ago', 'during'], a: 1, why: 'Since + a point in time.' },
      { m: 'You ___ wear a seatbelt. It’s the law.', o: ['must', 'can', 'might', 'would'], a: 0 },
      { m: 'I was ___ because the lesson was ___.', o: ['bored / boring', 'boring / bored', 'bored / bored', 'boring / boring'], a: 0, why: '-ed = how you feel; -ing = what causes it.' },
      { order: 'Where did you go on holiday last year', tr: '' },
      { order: 'Could you tell me the way to the museum', tr: '' },
    ],
    dictation: [
      ['I went to the beach with my friends last weekend.', ''],
      ['The train to Manchester leaves from platform four.', ''],
      ['I’ve got a headache and a sore throat.', ''],
      ['We were watching TV when the lights went out.', ''],
      ['I’m going to start a new job next month.', ''],
    ],
    dialogues: [
      {
        title: 'At the train station',
        lines: ['Hi, a ticket to Oxford, please.', 'Single or return?', 'Return, please. When’s the next train?', 'At ten forty-five, from platform two.', 'Great, thanks.'],
        questions: [
          ['What kind of ticket?', ['Single', 'Return', 'First class', 'Weekly'], 1],
          ['When is the next train?', ['10:15', '10:45', '11:45', '2:45'], 1],
          ['Which platform?', ['2', '4', '10', '12'], 0],
        ],
      },
      {
        title: 'At the doctor’s',
        lines: ['So, what seems to be the problem?', 'I’ve had a cough for a week and I feel very tired.', 'Have you got a temperature?', 'Yes, a little, since yesterday.', 'OK. Get some rest and drink lots of water. Come back if it gets worse.'],
        questions: [
          ['How long has the patient had a cough?', ['A day', 'Three days', 'A week', 'A month'], 2],
          ['Since when has the patient had a temperature?', ['Last week', 'Yesterday', 'This morning', 'He hasn’t'], 1],
          ['What does the doctor recommend?', ['Antibiotics', 'Rest and water', 'Going to hospital', 'Exercise'], 1],
        ],
      },
    ],
    repeat: [
      ['Could you tell me how to get to the city centre?', ''],
      ['I went to London last summer.', ''],
      ['I’ve had a headache since this morning.', ''],
      ['Can I try this on, please?', ''],
      ['What are you going to do this weekend?', ''],
    ],
    speak: [
      { prompt: 'What did you do last weekend?', targets: ['i went', 'i saw', 'on saturday', 'then'], seconds: 60 },
      { prompt: 'Describe your daily routine.', targets: ['i usually', 'i get up', 'after that', 'in the evening'], seconds: 60 },
      { prompt: 'Give directions from your home to a shop or station.', targets: ['turn left', 'turn right', 'go straight on', 'next to'], seconds: 45 },
      { prompt: 'Talk about your best holiday.', targets: ['we went', 'we stayed', 'it was', 'the best'], seconds: 60 },
    ],
  },
  B1: {
    vocab: [
      ['achieve', 'to succeed in doing something', 'She achieved her goal.'],
      ['improve', 'to get or make better', 'I want to improve my English.'],
      ['although', 'despite the fact that', 'Although it rained, we went out.'],
      ['however', 'but (at the start of a sentence)', 'However, the price is high.'],
      ['therefore', 'for that reason', 'He was ill; therefore, he stayed home.'],
      ['get used to', 'to become familiar with', 'I got used to the cold.'],
      ['look forward to', 'to be happy about something in the future', 'I look forward to meeting you.'],
      ['salary', 'the money you earn for a job', 'The salary is good.'],
      ['skill', 'an ability to do something well', 'Communication is a key skill.'],
      ['career', 'the jobs you do during your working life', 'She has a successful career.'],
      ['environment', 'the natural world', 'We must protect the environment.'],
      ['waste', 'to use badly; rubbish', 'Don’t waste water.'],
      ['find out', 'to discover information', 'I found out the truth.'],
      ['give up', 'to stop doing something', 'He gave up smoking.'],
      ['worth', 'good enough to justify the effort', 'The museum is worth visiting.'],
      ['challenge', 'something difficult that tests you', 'Learning a language is a challenge.'],
    ],
    grammar: [
      { c: 'I ___ here since 2020.', a: ["have lived", "'ve lived", 'have been living'], why: 'Present perfect with since/for.' },
      { c: 'Have you ever ___ sushi?', a: 'eaten', hint: 'eat', why: 'Present perfect for life experience: past participle.' },
      { c: 'If it rains tomorrow, we ___ at home.', a: ["will stay", "'ll stay"], why: 'First conditional: if + present, will + verb.' },
      { c: 'The man ___ car was stolen called the police.', a: 'whose', why: 'Whose = possession.' },
      { c: 'She said that she ___ tired.', a: 'was', why: 'Reported speech: am → was.' },
      { c: 'I’m used to ___ early.', a: 'getting up', why: 'Be used to + -ing.' },
      { c: 'The bridge ___ built in 1890.', a: 'was', why: 'Passive: was + past participle.' },
      { m: 'If I were you, I ___ apply for the job.', o: ['will', 'would', 'am', 'did'], a: 1, why: 'Advice: If I were you, I would…' },
      { m: 'I ___ go to the gym, but now I don’t.', o: ['used to', 'use to', 'am used to', 'was used'], a: 0 },
      { m: 'You ___ smoke here. It’s forbidden.', o: ["mustn't", "don't have to", "needn't", "shouldn't have"], a: 0, why: 'Mustn’t = prohibition; don’t have to = not necessary.' },
      { order: 'I have never been to the United States', tr: '' },
      { order: 'Would you mind opening the window', tr: '' },
    ],
    dictation: [
      ['I’ve been learning English for three years.', ''],
      ['If I have time, I’ll call you this evening.', ''],
      ['Although it was expensive, the trip was worth it.', ''],
      ['She told me she was looking for a new job.', ''],
      ['I’m really looking forward to the weekend.', ''],
    ],
    dialogues: [
      {
        title: 'A job interview',
        lines: [
          'Can you tell us a little about your experience?',
          'I’ve worked in customer service for four years, mainly with international clients.',
          'Why do you want to leave your current job?',
          'I’m looking for new challenges, and I’d like to develop my skills in marketing.',
          'When would you be available to start?',
          'From the beginning of next month.',
        ],
        questions: [
          ['How long has the candidate worked in customer service?', ['Two years', 'Three years', 'Four years', 'Five years'], 2],
          ['What area does the candidate want to develop?', ['Sales', 'Marketing', 'Finance', 'IT'], 1],
          ['When can the candidate start?', ['Immediately', 'Next week', 'Next month', 'Next year'], 2],
        ],
      },
      {
        title: 'Weekend plans',
        lines: [
          'Do you fancy going to the concert on Saturday?',
          'I’d love to, but I’m working until seven.',
          'That’s fine, it doesn’t start until nine.',
          'Great. Shall we meet outside the theatre?',
          'Perfect. See you there at half past eight.',
        ],
        questions: [
          ['Until when is the friend working?', ['5 pm', '7 pm', '8:30 pm', '9 pm'], 1],
          ['When does the concert start?', ['7 pm', '8 pm', '8:30 pm', '9 pm'], 3],
          ['What time will they meet?', ['7:00', '8:00', '8:30', '9:00'], 2],
        ],
      },
    ],
    repeat: [
      ['I’ve never been to Australia, but I’d love to go.', ''],
      ['If I were you, I’d talk to your manager.', ''],
      ['Although I was tired, I finished the report.', ''],
      ['I’m looking forward to hearing from you.', ''],
      ['Would you mind if I opened the window?', ''],
    ],
    speak: [
      { prompt: 'Tell a funny or surprising story from your life.', targets: ['i was', 'suddenly', 'in the end', 'when'], seconds: 90 },
      { prompt: 'What are your plans for the next five years?', targets: ["i'd like to", "i'm going to", 'i hope', 'i might'], seconds: 90 },
      { prompt: 'Is it better to live in the city or in the countryside? Give your opinion.', targets: ['i think', 'however', 'on the other hand', 'although'], seconds: 90 },
      { prompt: 'Describe a series or film you enjoyed and recommend it.', targets: ["it's about", 'the main character', 'i recommend', 'because'], seconds: 90 },
    ],
  },
  B2: {
    vocab: [
      ['inequality', 'an unfair difference between groups', 'Income inequality has grown.'],
      ['unemployment', 'the state of not having a job', 'Youth unemployment is high.'],
      ['carry out', 'to do or complete a task', 'They carried out a survey.'],
      ['despite', 'without being affected by', 'Despite the rain, we went out.'],
      ['as soon as', 'immediately when', 'I’ll call you as soon as I arrive.'],
      ['point of view', 'a way of looking at a situation', 'I respect your point of view.'],
      ['pull someone’s leg', 'to joke with someone', 'Relax, I’m just pulling your leg!'],
      ['put your foot in it', 'to say something embarrassing by mistake', 'I really put my foot in it.'],
      ['work-life balance', 'time divided between job and personal life', 'Remote work can help work-life balance.'],
      ['take advantage of', 'to make good use of', 'Take advantage of the sunny weather.'],
      ['drawback', 'a disadvantage', 'The main drawback is the cost.'],
      ['increasingly', 'more and more', 'It’s increasingly difficult to find a flat.'],
      ['make up your mind', 'to decide', 'I can’t make up my mind.'],
      ['get your act together', 'to start being organised', 'You need to get your act together.'],
      ['resource', 'a supply of something useful', 'Water is a precious resource.'],
      ['commute', 'to travel regularly to work', 'I commute an hour each way.'],
    ],
    grammar: [
      { c: 'If I ___ more money, I would travel the world.', a: 'had', why: 'Second conditional: if + past simple, would + verb.' },
      { c: 'If you had told me, I ___ have helped you.', a: 'would', why: 'Third conditional: would have + past participle.' },
      { c: 'I wish I ___ speak Japanese.', a: 'could', why: 'Wish + could for present abilities.' },
      { c: 'By next year, I ___ finished my degree.', a: ["will have", "'ll have"], why: 'Future perfect.' },
      { c: 'She asked me where I ___.', a: 'lived', why: 'Reported questions use statement word order.' },
      { c: 'The report ___ to be finished by Friday.', a: ['needs', 'has'], why: 'Needs/has to be + past participle.' },
      { c: 'I’ve been ___ for this job for months.', a: 'applying', why: 'Present perfect continuous.' },
      { m: 'I’d rather you ___ smoke in here.', o: ["don't", "didn't", "won't", "not"], a: 1, why: 'Would rather + subject + past simple.' },
      { m: 'He denied ___ the window.', o: ['to break', 'breaking', 'break', 'broke'], a: 1, why: 'Deny + -ing.' },
      { m: 'It’s high time we ___ a decision.', o: ['make', 'made', 'will make', 'have made'], a: 1, why: 'It’s (high) time + past simple.' },
      { order: 'If I had known the truth I would not have come', tr: '' },
      { order: 'Not only is it cheaper but it is also faster', tr: '' },
    ],
    dictation: [
      ['If I had more free time, I would learn to play the piano.', ''],
      ['Despite the difficulties, the project was a success.', ''],
      ['She asked me not to tell anyone about it.', ''],
      ['Increasingly, companies are allowing people to work from home.', ''],
      ['I wish I had listened to your advice.', ''],
    ],
    dialogues: [
      {
        title: 'Debate: remote work',
        lines: [
          'I think working from home really improves work-life balance.',
          'Maybe, but it can also be isolating. Lots of people miss their colleagues.',
          'True, although you save so much time not commuting.',
          'Perhaps the ideal is a hybrid model, two or three days at home and the rest in the office.',
        ],
        questions: [
          ['What advantage does the first speaker mention?', ['Higher pay', 'Better work-life balance', 'Fewer meetings', 'Better health'], 1],
          ['What drawback does the second speaker mention?', ['Isolation', 'Internet costs', 'Noise', 'Lower pay'], 0],
          ['What do they suggest?', ['Only home working', 'Only office work', 'A hybrid model', 'A four-day week'], 2],
        ],
      },
      {
        title: 'A complaint at a hotel',
        lines: [
          'Good evening. I’d like to complain. The air conditioning in my room isn’t working.',
          'I’m terribly sorry. I’ll send someone from maintenance right away.',
          'I appreciate that, but I already reported it yesterday and nobody came.',
          'In that case, we’ll move you to another room now, and breakfast is on us.',
        ],
        questions: [
          ['What is the problem?', ['A noisy room', 'Broken air conditioning', 'A dirty room', 'A wrong bill'], 1],
          ['Why is the guest annoyed?', ['It’s the first time', 'He reported it yesterday', 'The staff were rude', 'He lost his key'], 1],
          ['What does the hotel offer?', ['A refund', 'A new room and free breakfast', 'A discount', 'Late checkout'], 1],
        ],
      },
    ],
    repeat: [
      ['If I’d known earlier, I would have done things differently.', ''],
      ['From my point of view, it’s a question of priorities.', ''],
      ['Although I partly agree, I still have some doubts.', ''],
      ['It’s essential that we reach an agreement.', ''],
      ['I’ve been trying to change jobs for months.', ''],
    ],
    speak: [
      { prompt: 'What would you do if you won the lottery? Justify your choices.', targets: ['if i won', 'i would', 'i would invest', 'because'], seconds: 120 },
      { prompt: 'Discuss the pros and cons of social media.', targets: ['on the one hand', 'on the other hand', 'although', 'to sum up'], seconds: 120 },
      { prompt: 'Describe a mistake you made and what you would have done differently.', targets: ['if i had', 'i would have', 'i realised', 'i learnt'], seconds: 120 },
      { prompt: 'Make a phone complaint about a faulty product.', targets: ["i'd like to", "doesn't work", 'refund', 'replacement'], seconds: 90 },
    ],
  },
  C1: {
    vocab: [
      ['nevertheless', 'despite what has just been said', 'Nevertheless, the data are clear.'],
      ['it is worth noting', 'it is important to mention', 'It is worth noting that prices fell.'],
      ['ultimately', 'in the end; fundamentally', 'Ultimately, it’s your decision.'],
      ['underlying', 'real but not obvious', 'There is an underlying problem.'],
      ['gradually', 'slowly, over a period of time', 'The situation is gradually improving.'],
      ['entail', 'to involve as a necessary part', 'The job entails a lot of travel.'],
      ['exacerbate', 'to make worse', 'The crisis exacerbated unemployment.'],
      ['weigh up', 'to consider carefully', 'We need to weigh up the risks.'],
      ['in the wake of', 'as a result of / after', 'In the wake of the crisis, many firms closed.'],
      ['outspoken', 'saying openly what you think', 'She is very outspoken.'],
      ['in the spotlight', 'receiving a lot of public attention', 'The issue is in the spotlight.'],
      ['nuance', 'a very small difference in meaning', 'The text is full of nuance.'],
      ['approach', 'a way of dealing with something', 'Their approach is innovative.'],
      ['delve into', 'to examine in detail', 'Let’s delve into this question.'],
      ['albeit', 'although', 'It was a success, albeit a small one.'],
      ['hinder', 'to make progress difficult', 'Bureaucracy hinders innovation.'],
    ],
    grammar: [
      { c: 'Not only ___ he late, but he also forgot the documents.', a: 'was', why: 'Inversion after "Not only".' },
      { c: 'Had I ___, I would have acted differently.', a: 'known', why: 'Inverted third conditional: Had I + past participle.' },
      { c: 'Hardly ___ I arrived when it started to rain.', a: 'had', why: 'Inversion: Hardly had + subject + past participle… when.' },
      { c: 'He must ___ forgotten about the meeting.', a: 'have', why: 'Past deduction: must have + past participle.' },
      { c: 'However hard she ___, she couldn’t open it.', a: 'tried', why: 'However + adjective/adverb + subject + verb.' },
      { c: 'The proposal, ___ was rejected, will be revised.', a: 'which', why: 'Non-defining relative clause: which (never that).' },
      { m: 'The most formal equivalent of "find out" is…', o: ['ascertain', 'figure', 'look up', 'get'], a: 0 },
      { m: 'Should you ___ any questions, please contact us.', o: ['have', 'had', 'having', 'to have'], a: 0, why: 'Formal inverted conditional: Should you + base verb.' },
      { m: 'It is essential that every candidate ___ the form.', o: ['completes', 'complete', 'completed', 'will complete'], a: 1, why: 'Subjunctive after "essential that".' },
      { m: 'Little ___ that he was being watched.', o: ['he knew', 'did he know', 'he did know', 'knew he'], a: 1, why: 'Negative adverbial inversion.' },
      { order: 'It should be noted that the results are not conclusive', tr: '' },
      { order: 'Had I known I would have reacted differently', tr: '' },
    ],
    dictation: [
      ['It is worth noting that the measure has exacerbated the situation.', ''],
      ['However hard I try, I can’t seem to convince her.', ''],
      ['In the wake of the crisis, numerous companies went bankrupt.', ''],
      ['Nevertheless, these findings should be interpreted with caution.', ''],
      ['Ultimately, it is a problem of a political nature.', ''],
    ],
    dialogues: [
      {
        title: 'Radio interview',
        lines: [
          'Professor, what lies behind the rise in urban inequality?',
          'It’s a complex phenomenon. In the wake of soaring rents, many families have been forced out to the suburbs.',
          'And what measures would you propose?',
          'First and foremost, expanding social housing. Nevertheless, without efficient public transport, the problem would persist.',
        ],
        questions: [
          ['What triggered the change, according to the professor?', ['Soaring rents', 'Unemployment', 'Tourism', 'Immigration'], 0],
          ['What is her first proposal?', ['Lower taxes', 'More social housing', 'A rent freeze', 'New jobs'], 1],
          ['What else is needed?', ['Better schools', 'Efficient public transport', 'More police', 'Private investment'], 1],
        ],
      },
      {
        title: 'Team meeting',
        lines: [
          'Before we commit, we ought to weigh up the risks.',
          'I agree, but if we keep putting it off, we’ll miss the opportunity.',
          'I’m not saying we should drop it, just that we look into it more carefully.',
          'Then I suggest we put together a report by Thursday.',
        ],
        questions: [
          ['What does the first speaker want?', ['To cancel', 'To weigh up the risks', 'To decide now', 'To hire staff'], 1],
          ['What worries the second speaker?', ['The budget', 'Missing the opportunity', 'The deadline', 'Motivation'], 1],
          ['What is proposed in the end?', ['A Monday meeting', 'A report by Thursday', 'Dropping the idea', 'Asking the boss'], 1],
        ],
      },
    ],
    repeat: [
      ['I’d like to qualify what I’ve just said.', ''],
      ['However much you insist, I’m not changing my mind.', ''],
      ['One might well ask whether this measure is effective.', ''],
      ['Ultimately, it’s about striking the right balance.', ''],
      ['Had I known, I would have reacted differently.', ''],
    ],
    speak: [
      { prompt: 'In three minutes, present a social issue in your country: causes and possible solutions.', targets: ['it is worth noting', 'in the wake of', 'nevertheless', 'ultimately'], seconds: 180 },
      { prompt: 'Argue convincingly for an unpopular opinion.', targets: ['albeit', 'however much', 'admittedly', 'in my view'], seconds: 150 },
      { prompt: 'Role-play: negotiate a pay rise with your manager.', targets: ["i'd like to raise", 'bearing in mind', 'i propose', 'in return'], seconds: 150 },
      { prompt: 'Discuss a book or article that changed your mind about something.', targets: ['it argues', 'it led me to', 'nuance', 'delve into'], seconds: 150 },
    ],
  },
};

export const englishExercises: Exercise[] = (Object.keys(EN) as BankLevel[]).flatMap((level) => buildLevel('en', level, EN[level]));
