import type { BankLevel, Exercise } from '../../exercises/types';
import { buildLevel, type LevelBankSource } from './builders';

/** Spanish exercise bank, A1 → C1. */
const ES: Record<BankLevel, LevelBankSource> = {
  A1: {
    vocab: [
      ['la familia', 'family', 'Mi familia es grande.'],
      ['el hermano', 'brother', 'Tengo un hermano.'],
      ['la madre', 'mother', 'Mi madre se llama Ana.'],
      ['el agua', 'water', 'Un vaso de agua, por favor.'],
      ['el pan', 'bread', 'Compro pan todos los días.'],
      ['la casa', 'house', 'Mi casa es pequeña.'],
      ['la calle', 'street', 'Vivo en esta calle.'],
      ['comer', 'to eat', 'Como a las dos.'],
      ['beber', 'to drink', 'Bebo café por la mañana.'],
      ['vivir', 'to live', 'Vivo en Madrid.'],
      ['hablar', 'to speak', 'Hablo un poco de español.'],
      ['hoy', 'today', 'Hoy es lunes.'],
      ['mañana', 'tomorrow', 'Mañana trabajo.'],
      ['barato', 'cheap', 'El pan es barato.'],
      ['caro', 'expensive', 'El hotel es caro.'],
      ['¿cuánto cuesta?', 'how much does it cost?', '¿Cuánto cuesta el billete?'],
    ],
    grammar: [
      { c: 'Yo ___ de Francia.', a: 'soy', why: 'Ser expresses origin: soy de…' },
      { c: 'Nosotros ___ en Barcelona.', a: 'vivimos', hint: 'vivir', why: '-ir verbs: vivimos for nosotros.' },
      { c: 'Ella ___ veinte años.', a: 'tiene', hint: 'tener', why: 'Age uses tener, not ser.' },
      { c: '¿Dónde ___ el baño?', a: 'está', why: 'Location of a specific thing uses estar.' },
      { c: 'Me ___ el chocolate.', a: 'gusta', why: 'Gusta with a singular noun.' },
      { c: 'Me ___ los perros.', a: 'gustan', why: 'Gustan with a plural noun.' },
      { m: '___ un supermercado cerca de aquí?', o: ['¿Hay', '¿Está', '¿Es', '¿Tiene'], a: 0, why: 'Hay = there is/are (existence).' },
      { m: 'Choose the correct article: ___ problema', o: ['la', 'el', 'los', 'una'], a: 1, why: 'Problema is masculine despite ending in -a.' },
      { m: 'Tú ___ español muy bien.', o: ['hablo', 'hablas', 'habla', 'hablan'], a: 1 },
      { order: 'Me llamo Laura y soy profesora', tr: 'My name is Laura and I am a teacher' },
      { order: '¿Cuántos años tienes tú?', tr: 'How old are you?' },
    ],
    dictation: [
      ['Hola, me llamo Pablo.', 'Hello, my name is Pablo.'],
      ['Vivo en una casa pequeña.', 'I live in a small house.'],
      ['Mi hermana tiene diez años.', 'My sister is ten years old.'],
      ['Un café con leche, por favor.', 'A coffee with milk, please.'],
      ['Hoy es martes.', 'Today is Tuesday.'],
    ],
    dialogues: [
      {
        title: 'En la cafetería',
        lines: ['Buenos días. ¿Qué quiere tomar?', 'Un café con leche y un cruasán, por favor.', 'Muy bien. ¿Algo más?', 'No, gracias. ¿Cuánto es?', 'Son tres euros con cincuenta.'],
        questions: [
          ['What does the customer order?', ['Tea and a sandwich', 'A coffee with milk and a croissant', 'Orange juice', 'Two coffees'], 1],
          ['How much does it cost?', ['€3.15', '€2.50', '€3.50', '€13.50'], 2],
          ['Does the customer want anything else?', ['Yes, water', 'No', 'Yes, a cake', 'We don’t know'], 1],
        ],
      },
      {
        title: 'Presentaciones',
        lines: ['Hola, soy Marta. ¿Y tú?', 'Hola, me llamo Tom. Soy de Londres.', '¿Vives aquí en Sevilla?', 'Sí, vivo aquí. Trabajo en un hotel.'],
        questions: [
          ['Where is Tom from?', ['Seville', 'London', 'Madrid', 'Dublin'], 1],
          ['Where does Tom work?', ['In a school', 'In a shop', 'In a hotel', 'In a restaurant'], 2],
          ['Where does Tom live now?', ['In Seville', 'In London', 'In a hotel', 'In Marta’s house'], 0],
        ],
      },
    ],
    repeat: [
      ['Buenos días, ¿cómo está usted?', 'Good morning, how are you? (formal)'],
      ['Mucho gusto.', 'Nice to meet you.'],
      ['¿Dónde está la estación?', 'Where is the station?'],
      ['No entiendo. ¿Puede repetir, por favor?', 'I don’t understand. Can you repeat, please?'],
      ['Me gusta mucho la comida española.', 'I really like Spanish food.'],
    ],
    speak: [
      { prompt: 'Preséntate: nombre, origen, ciudad. (Introduce yourself: name, origin, city.)', targets: ['me llamo', 'soy de', 'vivo en'], seconds: 45, model: 'Hola, me llamo Sara. Soy de Francia y vivo en Lyon.' },
      { prompt: 'Describe a tu familia. (Describe your family.)', targets: ['tengo', 'se llama', 'años'], seconds: 60, model: 'Tengo un hermano. Se llama Luis y tiene doce años.' },
      { prompt: '¿Qué te gusta comer y beber? (What do you like to eat and drink?)', targets: ['me gusta', 'me gustan', 'no me gusta'], seconds: 45 },
      { prompt: 'Pide algo en una cafetería. (Order something in a café.)', targets: ['quiero', 'por favor', 'cuánto'], seconds: 30, model: 'Hola, quiero un café, por favor. ¿Cuánto es?' },
    ],
  },
  A2: {
    vocab: [
      ['el billete', 'ticket', 'Compré un billete de tren.'],
      ['el viaje', 'trip', 'El viaje fue muy largo.'],
      ['la playa', 'beach', 'Fuimos a la playa el sábado.'],
      ['el médico', 'doctor', 'Tengo que ir al médico.'],
      ['doler', 'to hurt', 'Me duele la cabeza.'],
      ['cansado', 'tired', 'Estoy muy cansado hoy.'],
      ['el fin de semana', 'weekend', '¿Qué hiciste el fin de semana?'],
      ['ayer', 'yesterday', 'Ayer comí paella.'],
      ['la semana pasada', 'last week', 'La semana pasada estuve en Roma.'],
      ['alquilar', 'to rent', 'Alquilamos un coche.'],
      ['reservar', 'to book', 'Quiero reservar una mesa.'],
      ['a la derecha', 'to the right', 'El banco está a la derecha.'],
      ['todo recto', 'straight ahead', 'Siga todo recto.'],
      ['la ropa', 'clothes', 'Necesito comprar ropa.'],
      ['probarse', 'to try on', '¿Puedo probarme esta camisa?'],
      ['a menudo', 'often', 'Voy al cine a menudo.'],
    ],
    grammar: [
      { c: 'Ayer ___ al cine con Ana.', a: 'fui', hint: 'ir', why: 'Pretérito indefinido of ir: fui.' },
      { c: 'El sábado nosotros ___ una paella.', a: 'comimos', hint: 'comer' },
      { c: '¿Qué ___ tú el fin de semana?', a: 'hiciste', hint: 'hacer', why: 'Irregular: hice, hiciste, hizo…' },
      { c: 'Cuando era niño, ___ en un pueblo.', a: 'vivía', hint: 'vivir', why: 'Imperfecto for past habits and background.' },
      { c: 'Mañana ___ a visitar a mis abuelos.', a: 'voy', why: 'Ir a + infinitive for plans.' },
      { c: '¿La película? Ya ___ he visto.', a: 'la', why: 'Direct object pronoun for a feminine noun.' },
      { c: 'Mi hermano es ___ alto ___ mi padre.', a: ['más', 'que'], why: 'más + adjective + que' },
      { m: 'Todos los días me ___ a las siete.', o: ['levanto', 'levanta', 'levanté', 'levantaba'], a: 0, why: 'Reflexive verb in present: me levanto.' },
      { m: '___ un año, viajé a México.', o: ['Desde', 'Hace', 'Hacía', 'Durante'], a: 1, why: 'Hace + time = … ago.' },
      { m: 'Choose the imperative (tú): ___ la ventana, por favor.', o: ['Abres', 'Abre', 'Abrir', 'Abra'], a: 1 },
      { order: 'El año pasado fuimos a la playa', tr: 'Last year we went to the beach' },
      { order: '¿Me puede traer la cuenta?', tr: 'Can you bring me the bill?' },
    ],
    dictation: [
      ['Ayer fui al mercado con mi madre.', 'Yesterday I went to the market with my mother.'],
      ['Me duele mucho la cabeza.', 'My head hurts a lot.'],
      ['El tren sale a las ocho y media.', 'The train leaves at half past eight.'],
      ['Quiero reservar una habitación doble.', 'I want to book a double room.'],
      ['Cuando era pequeño, jugaba al fútbol.', 'When I was little, I played football.'],
    ],
    dialogues: [
      {
        title: 'En la estación',
        lines: ['Hola, un billete para Toledo, por favor.', '¿De ida y vuelta?', 'No, solo de ida. ¿A qué hora sale el próximo tren?', 'Sale a las once y cuarto, del andén tres.', 'Perfecto, gracias.'],
        questions: [
          ['What kind of ticket does the traveller buy?', ['Return', 'One-way', 'First class', 'Monthly pass'], 1],
          ['When does the next train leave?', ['11:15', '11:45', '3:15', '10:15'], 0],
          ['Which platform?', ['1', '2', '3', '13'], 2],
        ],
      },
      {
        title: 'El fin de semana',
        lines: ['¿Qué hiciste el fin de semana?', 'Fui a la montaña con unos amigos. ¿Y tú?', 'Yo me quedé en casa. Estaba enfermo.', 'Vaya, ¿qué te pasó?', 'Me dolía la garganta, pero ya estoy mejor.'],
        questions: [
          ['Where did the second speaker go?', ['To the beach', 'To the mountains', 'To a party', 'To the doctor'], 1],
          ['Why did the first speaker stay home?', ['He was ill', 'It rained', 'He was working', 'He was tired'], 0],
          ['What hurt?', ['His head', 'His back', 'His throat', 'His leg'], 2],
        ],
      },
    ],
    repeat: [
      ['Perdone, ¿cómo llego al centro?', 'Excuse me, how do I get to the centre?'],
      ['El fin de semana pasado fui a la playa.', 'Last weekend I went to the beach.'],
      ['Me duele la espalda desde ayer.', 'My back has hurt since yesterday.'],
      ['¿Puedo probarme estos pantalones?', 'Can I try on these trousers?'],
      ['Normalmente me levanto a las siete.', 'I normally get up at seven.'],
    ],
    speak: [
      { prompt: '¿Qué hiciste el fin de semana pasado? (What did you do last weekend?)', targets: ['fui', 'comí', 'vi', 'el sábado'], seconds: 60 },
      { prompt: 'Describe tu rutina diaria. (Describe your daily routine.)', targets: ['me levanto', 'desayuno', 'después', 'por la noche'], seconds: 60 },
      { prompt: 'Explica cómo llegar de tu casa a una tienda. (Give directions from your home to a shop.)', targets: ['todo recto', 'a la derecha', 'a la izquierda', 'gire'], seconds: 45 },
      { prompt: '¿Cómo era tu vida cuando eras niño/a? (What was your life like as a child?)', targets: ['vivía', 'tenía', 'jugaba', 'era'], seconds: 60 },
    ],
  },
  B1: {
    vocab: [
      ['la experiencia', 'experience', 'Fue una experiencia inolvidable.'],
      ['el medio ambiente', 'the environment', 'Hay que proteger el medio ambiente.'],
      ['desarrollar', 'to develop', 'Quiero desarrollar mis habilidades.'],
      ['el sueldo', 'salary', 'El sueldo no es muy alto.'],
      ['la entrevista', 'interview', 'Mañana tengo una entrevista de trabajo.'],
      ['darse cuenta', 'to realise', 'Me di cuenta de mi error.'],
      ['echar de menos', 'to miss (someone)', 'Echo de menos a mi familia.'],
      ['por lo tanto', 'therefore', 'Llovía; por lo tanto, nos quedamos.'],
      ['sin embargo', 'however', 'Es caro; sin embargo, lo compro.'],
      ['además', 'moreover', 'Además, es muy simpático.'],
      ['acostumbrarse', 'to get used to', 'Me acostumbré al clima.'],
      ['la costumbre', 'custom / habit', 'Es una costumbre muy antigua.'],
      ['el reto', 'challenge', 'Aprender un idioma es un reto.'],
      ['valer la pena', 'to be worth it', 'Vale la pena visitarlo.'],
      ['quedar con', 'to meet up with', 'He quedado con Marta a las seis.'],
      ['el éxito', 'success', 'La película fue un éxito.'],
    ],
    grammar: [
      { c: 'Espero que ___ buen tiempo mañana.', a: 'haga', hint: 'hacer', why: 'Esperar que + presente de subjuntivo.' },
      { c: 'Quiero que tú ___ conmigo.', a: 'vengas', hint: 'venir' },
      { c: 'No creo que Juan ___ razón.', a: 'tenga', hint: 'tener', why: 'No creo que + subjuntivo (doubt).' },
      { c: 'Este regalo es ___ ti.', a: 'para', why: 'Para = recipient/purpose.' },
      { c: 'Gracias ___ tu ayuda.', a: 'por', why: 'Por = cause/exchange.' },
      { c: 'Esta mañana ___ un café con Ana.', a: ['he tomado', 'tomé'], hint: 'tomar', why: 'Spain: pretérito perfecto for today; LatAm: tomé.' },
      { c: 'Mientras ___ la cena, sonó el teléfono.', a: 'preparaba', hint: 'preparar', why: 'Imperfecto for the ongoing background action.' },
      { c: 'El chico ___ te hablé es mi primo.', a: ['del que', 'de quien'], why: 'Relative pronoun after a preposition.' },
      { m: 'Si tengo tiempo, ___ al gimnasio.', o: ['iría', 'iré', 'fuera', 'vaya'], a: 1, why: 'Real condition: si + presente, futuro.' },
      { m: 'Me dijo que ___ cansado.', o: ['está', 'estaba', 'esté', 'estará'], a: 1, why: 'Reported speech shifts present → imperfecto.' },
      { m: 'En tu lugar, yo ___ más.', o: ['estudio', 'estudiaré', 'estudiaría', 'estudie'], a: 2, why: 'Condicional for advice.' },
      { order: 'Cuando llegues a casa llámame por favor', tr: 'When you get home call me please' },
      { order: 'Nunca he estado en Argentina', tr: 'I have never been to Argentina' },
    ],
    dictation: [
      ['Me di cuenta de que había perdido las llaves.', 'I realised I had lost my keys.'],
      ['Espero que te guste el regalo.', 'I hope you like the present.'],
      ['Sin embargo, decidimos seguir adelante.', 'However, we decided to keep going.'],
      ['Echo mucho de menos a mis amigos.', 'I really miss my friends.'],
      ['Nunca he probado la comida peruana.', 'I have never tried Peruvian food.'],
    ],
    dialogues: [
      {
        title: 'Una entrevista de trabajo',
        lines: [
          'Cuéntenos un poco sobre su experiencia.',
          'He trabajado tres años en atención al cliente, sobre todo con clientes internacionales.',
          '¿Por qué quiere cambiar de trabajo?',
          'Busco nuevos retos y me gustaría desarrollar mis habilidades en ventas.',
          'Muy bien. ¿Cuándo podría empezar?',
          'A partir del mes que viene.',
        ],
        questions: [
          ['How long has the candidate worked in customer service?', ['One year', 'Two years', 'Three years', 'Five years'], 2],
          ['Why does the candidate want to change jobs?', ['Better salary', 'New challenges', 'Moving city', 'Problems with the boss'], 1],
          ['When can the candidate start?', ['Tomorrow', 'Next week', 'Next month', 'In a year'], 2],
        ],
      },
      {
        title: 'Planes para el sábado',
        lines: [
          '¿Te apetece ir al concierto el sábado?',
          'Me encantaría, pero tengo que trabajar hasta las ocho.',
          'No pasa nada, empieza a las diez.',
          'Entonces sí. ¿Quedamos delante del teatro?',
          'Perfecto. Te espero allí a las nueve y media.',
        ],
        questions: [
          ['Until what time does the friend work?', ['6 pm', '8 pm', '9:30 pm', '10 pm'], 1],
          ['When does the concert start?', ['At 8', 'At 9', 'At 9:30', 'At 10'], 3],
          ['Where will they meet?', ['At home', 'In front of the theatre', 'At a bar', 'At work'], 1],
        ],
      },
    ],
    repeat: [
      ['Me alegro mucho de que hayas venido.', 'I’m so glad you came.'],
      ['Creo que vale la pena intentarlo.', 'I think it’s worth trying.'],
      ['Cuando era estudiante, vivía con tres amigos.', 'When I was a student, I lived with three friends.'],
      ['¿Qué harías tú en mi lugar?', 'What would you do in my place?'],
      ['Sin embargo, no estoy del todo de acuerdo.', 'However, I don’t completely agree.'],
    ],
    speak: [
      { prompt: 'Cuenta una anécdota divertida o sorprendente de tu vida.', targets: ['era', 'estaba', 'de repente', 'al final'], seconds: 90 },
      { prompt: '¿Cuáles son tus planes para los próximos cinco años?', targets: ['me gustaría', 'espero que', 'voy a', 'cuando'], seconds: 90 },
      { prompt: 'Da tu opinión: ¿es mejor vivir en el campo o en la ciudad?', targets: ['creo que', 'no creo que', 'sin embargo', 'además'], seconds: 90 },
      { prompt: 'Describe una serie o película que te haya gustado.', targets: ['trata de', 'me gustó', 'el protagonista', 'recomiendo'], seconds: 90 },
    ],
  },
  B2: {
    vocab: [
      ['la desigualdad', 'inequality', 'La desigualdad ha aumentado.'],
      ['el desempleo', 'unemployment', 'El desempleo juvenil es alto.'],
      ['plantear', 'to raise (an issue)', 'Quiero plantear una pregunta.'],
      ['llevar a cabo', 'to carry out', 'Llevaron a cabo un estudio.'],
      ['a pesar de', 'despite', 'A pesar de la lluvia, salimos.'],
      ['de hecho', 'in fact', 'De hecho, ya lo sabía.'],
      ['el punto de vista', 'point of view', 'Respeto tu punto de vista.'],
      ['tomar el pelo', 'to pull someone’s leg', '¡Me estás tomando el pelo!'],
      ['meter la pata', 'to put your foot in it', 'Metí la pata en la reunión.'],
      ['la conciliación', 'work-life balance', 'La conciliación es difícil.'],
      ['aprovechar', 'to make the most of', 'Hay que aprovechar el tiempo.'],
      ['en cuanto', 'as soon as', 'Te llamo en cuanto llegue.'],
      ['el recurso', 'resource', 'Los recursos naturales son limitados.'],
      ['suponer', 'to involve / to suppose', 'Supone un gran esfuerzo.'],
      ['ponerse las pilas', 'to get your act together', 'Tienes que ponerte las pilas.'],
      ['cada vez más', 'more and more', 'Cada vez más gente teletrabaja.'],
    ],
    grammar: [
      { c: 'Si ___ más dinero, viajaría por todo el mundo.', a: 'tuviera', hint: 'tener', why: 'Hypothetical: si + imperfecto de subjuntivo, condicional.' },
      { c: 'Si me lo hubieras dicho, te ___ ayudado.', a: 'habría', why: 'Past unreal: si + pluscuamperfecto subj., condicional compuesto.' },
      { c: 'Me pidió que le ___ con la mudanza.', a: 'ayudara', hint: 'ayudar', why: 'Past trigger → imperfecto de subjuntivo.' },
      { c: 'Te llamaré en cuanto ___ a casa.', a: 'llegue', hint: 'llegar', why: 'Future time clause → subjuntivo.' },
      { c: 'Llevo tres años ___ español.', a: 'estudiando', why: 'Llevar + time + gerundio.' },
      { c: 'Aunque ___ mañana, iremos a la playa.', a: 'llueva', hint: 'llover', why: 'Aunque + subjuntivo for an unknown/hypothetical fact.' },
      { c: 'Se ___ muchas casas en esta zona el año pasado.', a: 'construyeron', why: 'Pasiva refleja agrees with the plural noun.' },
      { m: 'Busco un piso que ___ cerca del trabajo.', o: ['está', 'esté', 'estará', 'estuvo'], a: 1, why: 'Unknown antecedent → subjuntivo.' },
      { m: 'Ojalá ___ venir ayer.', o: ['puedes', 'pudieras', 'hubieras podido', 'puedas'], a: 2, why: 'Regret about the past: ojalá + pluscuamperfecto de subjuntivo.' },
      { m: 'Choose the correct meaning: "Es muy listo"', o: ['He’s ready', 'He’s clever', 'He’s fast', 'He’s finished'], a: 1, why: 'Ser listo = clever; estar listo = ready.' },
      { order: 'Si hubiera sabido la verdad no habría venido', tr: 'If I had known the truth I would not have come' },
      { order: 'Es importante que todos participen en el debate', tr: 'It is important that everyone takes part in the debate' },
    ],
    dictation: [
      ['Si tuviera más tiempo, aprendería a tocar la guitarra.', 'If I had more time, I would learn to play the guitar.'],
      ['A pesar de las dificultades, el proyecto salió adelante.', 'Despite the difficulties, the project went ahead.'],
      ['Me pidió que no se lo contara a nadie.', 'She asked me not to tell anyone.'],
      ['Cada vez más empresas permiten el teletrabajo.', 'More and more companies allow remote work.'],
      ['De hecho, el desempleo ha bajado este año.', 'In fact, unemployment has fallen this year.'],
    ],
    dialogues: [
      {
        title: 'Debate: el teletrabajo',
        lines: [
          'Yo creo que el teletrabajo mejora la conciliación familiar.',
          'Puede ser, pero también aísla a los trabajadores. Muchos echan de menos a sus compañeros.',
          'Es cierto, aunque se ahorra mucho tiempo en desplazamientos.',
          'Quizás lo ideal sea un modelo mixto: dos o tres días en casa y el resto en la oficina.',
        ],
        questions: [
          ['What advantage does the first speaker mention?', ['Higher salary', 'Better work-life balance', 'More meetings', 'Better health'], 1],
          ['What disadvantage does the second speaker mention?', ['Isolation', 'Cost of internet', 'Noise at home', 'Lower productivity'], 0],
          ['What do they suggest in the end?', ['Only remote work', 'Only office work', 'A hybrid model', 'A four-day week'], 2],
        ],
      },
      {
        title: 'Una queja en el hotel',
        lines: [
          'Buenas noches. Quería quejarme: el aire acondicionado de mi habitación no funciona.',
          'Lo siento mucho. Enviaré a alguien de mantenimiento enseguida.',
          'Se lo agradezco, pero ya lo pedí ayer y nadie vino.',
          'Entonces le cambiamos de habitación ahora mismo, y le ofrecemos el desayuno gratis.',
        ],
        questions: [
          ['What is the problem?', ['The room is noisy', 'The air conditioning doesn’t work', 'The room is dirty', 'The bill is wrong'], 1],
          ['Why is the guest annoyed?', ['It’s the first time', 'He already asked yesterday', 'The staff were rude', 'He lost his key'], 1],
          ['What does the hotel offer?', ['A refund', 'A new room and free breakfast', 'A discount on the next stay', 'A late checkout'], 1],
        ],
      },
    ],
    repeat: [
      ['Si lo hubiera sabido antes, habría actuado de otra manera.', 'If I had known earlier, I would have acted differently.'],
      ['Desde mi punto de vista, es una cuestión de prioridades.', 'From my point of view, it’s a question of priorities.'],
      ['Aunque estoy de acuerdo en parte, tengo algunas dudas.', 'Although I partly agree, I have some doubts.'],
      ['Es fundamental que lleguemos a un acuerdo.', 'It’s essential that we reach an agreement.'],
      ['Llevo meses intentando cambiar de trabajo.', 'I’ve been trying to change jobs for months.'],
    ],
    speak: [
      { prompt: '¿Qué harías si te tocara la lotería? Justifica tus decisiones.', targets: ['si me tocara', 'compraría', 'invertiría', 'porque'], seconds: 120 },
      { prompt: 'Ventajas e inconvenientes de las redes sociales. Da argumentos a favor y en contra.', targets: ['por un lado', 'por otro lado', 'aunque', 'en conclusión'], seconds: 120 },
      { prompt: 'Cuenta un error que cometiste y qué habrías hecho de otra manera.', targets: ['si hubiera', 'habría', 'me di cuenta', 'aprendí'], seconds: 120 },
      { prompt: 'Haz una reclamación por teléfono sobre un producto defectuoso.', targets: ['quería', 'no funciona', 'me gustaría que', 'devolver'], seconds: 90 },
    ],
  },
  C1: {
    vocab: [
      ['no obstante', 'nevertheless', 'No obstante, los datos son claros.'],
      ['cabe destacar', 'it is worth noting', 'Cabe destacar el papel de la prensa.'],
      ['en definitiva', 'in short / ultimately', 'En definitiva, fue un éxito.'],
      ['subyacente', 'underlying', 'Hay un problema subyacente.'],
      ['paulatinamente', 'gradually', 'La situación mejora paulatinamente.'],
      ['acarrear', 'to entail / bring about', 'Esa decisión acarreará consecuencias.'],
      ['agravar', 'to worsen', 'La crisis agravó el desempleo.'],
      ['la índole', 'nature / kind', 'Problemas de índole económica.'],
      ['ponderar', 'to weigh up', 'Hay que ponderar los riesgos.'],
      ['desembocar en', 'to lead to / result in', 'El conflicto desembocó en una huelga.'],
      ['a raíz de', 'as a result of', 'A raíz de la crisis, cerró la empresa.'],
      ['no tener pelos en la lengua', 'to be outspoken', 'Ella no tiene pelos en la lengua.'],
      ['estar en el candelero', 'to be in the limelight', 'El tema está en el candelero.'],
      ['matizar', 'to qualify / nuance', 'Me gustaría matizar lo que he dicho.'],
      ['el planteamiento', 'approach', 'Su planteamiento es innovador.'],
      ['ahondar en', 'to delve into', 'Conviene ahondar en esta cuestión.'],
    ],
    grammar: [
      { c: 'Por mucho que ___, no lo convencerás.', a: 'insistas', hint: 'insistir', why: 'Concessive "por mucho que" + subjuntivo.' },
      { c: '___ lo que ___, no cambiaré de opinión.', a: [['Digan'], ['digan']], why: 'Reduplicative structure: subjuntivo + lo que + subjuntivo.' },
      { c: 'No ha llegado todavía; ___ habido un atasco.', a: 'habrá', why: 'Futuro compuesto for probability in the past.' },
      { c: 'De ___ sabido, no habría aceptado el puesto.', a: 'haberlo', why: 'De + infinitivo compuesto = conditional "if I had…".' },
      { c: 'No es que no ___, es que no puedo.', a: 'quiera', hint: 'querer', why: '"No es que" + subjuntivo.' },
      { c: 'Serían las tres cuando ___ el teléfono.', a: 'sonó', why: 'Condicional for past probability; the event in indefinido.' },
      { m: 'The most formal equivalent of "hacer un análisis" is…', o: ['realizar un análisis', 'montar un análisis', 'echar un análisis', 'dar un análisis'], a: 0 },
      { m: '___ cansado que estuviera, terminaba siempre el trabajo.', o: ['Aunque', 'Por muy', 'Si bien', 'Pese'], a: 1, why: 'Por muy + adjetivo + que + subjuntivo.' },
      { m: 'Choose the correct register: in a formal report, "and also" becomes…', o: ['y encima', 'asimismo', 'y tal', 'y eso'], a: 1 },
      { m: 'Como no ___ a tiempo, perderemos el contrato.', o: ['entregamos', 'entreguemos', 'entregaremos', 'entregábamos'], a: 1, why: '"Como" + subjuntivo = threat/warning condition.' },
      { order: 'Cabe señalar que los resultados no son concluyentes', tr: 'It should be noted that the results are not conclusive' },
      { order: 'De haberlo sabido habría actuado de otra manera', tr: 'Had I known I would have acted differently' },
    ],
    dictation: [
      ['Cabe destacar que la medida ha agravado la situación.', 'It is worth noting that the measure has made the situation worse.'],
      ['Por mucho que lo intente, no consigo convencerla.', 'However hard I try, I can’t convince her.'],
      ['A raíz de la crisis, numerosas empresas cerraron.', 'As a result of the crisis, many companies closed.'],
      ['No obstante, conviene matizar estos resultados.', 'Nevertheless, these results should be qualified.'],
      ['En definitiva, se trata de un problema de índole política.', 'In short, it is a problem of a political nature.'],
    ],
    dialogues: [
      {
        title: 'Entrevista radiofónica',
        lines: [
          'Profesora, ¿a qué se debe el aumento de la desigualdad en las ciudades?',
          'Es un fenómeno complejo. A raíz de la subida de los alquileres, muchas familias se han visto obligadas a trasladarse a la periferia.',
          '¿Y qué medidas propondría?',
          'Ante todo, ampliar la vivienda pública. No obstante, sin una política de transporte eficaz, el problema persistiría.',
        ],
        questions: [
          ['According to the professor, what triggered the change?', ['Rising rents', 'Unemployment', 'Tourism', 'Immigration'], 0],
          ['What is the first measure she proposes?', ['Lower taxes', 'More public housing', 'Rent bans', 'New jobs'], 1],
          ['What else is needed for the measure to work?', ['Better schools', 'Efficient public transport', 'More police', 'Private investment'], 1],
        ],
      },
      {
        title: 'Reunión de equipo',
        lines: [
          'Antes de tomar una decisión, convendría ponderar los riesgos.',
          'Estoy de acuerdo, pero si seguimos aplazándolo, perderemos la oportunidad.',
          'No digo que lo descartemos, sino que lo estudiemos con más detenimiento.',
          'Entonces propongo que preparemos un informe para el jueves.',
        ],
        questions: [
          ['What does the first speaker want?', ['To cancel the project', 'To weigh up the risks first', 'To decide immediately', 'To hire more staff'], 1],
          ['What is the second speaker worried about?', ['The budget', 'Losing the opportunity', 'The deadline for the report', 'The team’s motivation'], 1],
          ['What is finally proposed?', ['A meeting on Monday', 'A report for Thursday', 'Dropping the idea', 'Asking the boss'], 1],
        ],
      },
    ],
    repeat: [
      ['Me gustaría matizar lo que acabo de decir.', 'I’d like to qualify what I’ve just said.'],
      ['Por mucho que insistas, no pienso cambiar de opinión.', 'However much you insist, I won’t change my mind.'],
      ['Cabe preguntarse si esta medida es realmente eficaz.', 'One may wonder whether this measure is really effective.'],
      ['En definitiva, se trata de encontrar un equilibrio.', 'Ultimately, it’s about finding a balance.'],
      ['De haberlo sabido, habría reaccionado de otra forma.', 'Had I known, I would have reacted differently.'],
    ],
    speak: [
      { prompt: 'Presenta en tres minutos un problema social de tu país, sus causas y posibles soluciones.', targets: ['cabe destacar', 'a raíz de', 'no obstante', 'en definitiva'], seconds: 180 },
      { prompt: 'Defiende una opinión impopular de forma convincente.', targets: ['si bien', 'por mucho que', 'conviene', 'en mi opinión'], seconds: 150 },
      { prompt: 'Simula una negociación: pide un aumento de sueldo a tu jefe/a.', targets: ['me gustaría plantear', 'teniendo en cuenta', 'propongo', 'a cambio'], seconds: 150 },
      { prompt: 'Comenta un libro o artículo que te haya hecho cambiar de opinión.', targets: ['plantea', 'me llevó a', 'matizar', 'ahondar'], seconds: 150 },
    ],
  },
};

export const spanishExercises: Exercise[] = (Object.keys(ES) as BankLevel[]).flatMap((level) => buildLevel('es', level, ES[level]));
